# Generated by Django 5.0.3 on 2024-03-09 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0008_adminfeedback_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminfeedback',
            name='created_at',
        ),
        migrations.AddField(
            model_name='adminfeedback',
            name='employee',
            field=models.ForeignKey(default=1223, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminfeedback',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'staff'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
